"""initial migration

Revision ID: 8b50566e71b2
Revises: 
Create Date: 2024-10-12 16:24:29.082296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b50566e71b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_transcript_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_metadata', sa.JSON(), nullable=True),
    sa.Column('transcript_text', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_newsapi_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_response', sa.JSON(), nullable=True),
    sa.Column('transcript_text', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_newsapi_data')
    op.drop_table('raw_transcript_data')
    # ### end Alembic commands ###
